# Generated by Django 3.2.13 on 2022-07-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20220519_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
