# Generated by Django 3.2.13 on 2022-05-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
    ]
