# Generated by Django 3.2.13 on 2022-05-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('calorie', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
