# Generated by Django 3.2.13 on 2022-08-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='calorie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
