# Generated by Django 3.2.13 on 2022-08-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20220813_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
